package com.ludoscity.findmybikes.data.database.tracking

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Ignore
import androidx.room.PrimaryKey
import com.ludoscity.findmybikes.utils.Utils
import java.text.SimpleDateFormat
import java.util.*

/**
 * Created by F8Full on 2019-06-24. This file is part of #findmybikes
 * A data model class to handle tracking datapoints. Base class only defining the key, a timestamp and
 * upload status for saving in Room
 */
@Entity                                         //Transient so that Gson ignores it but not Room (@columnInfo present)
abstract class BaseTrackingDatapoint constructor(@Transient @ColumnInfo(name = "id") @PrimaryKey(autoGenerate = true) var id: Int, //TODO: Room made me make it var ?
                                                 var timestamp: String, //TODO: Room made me make it var ?
                                                 @Transient var filenamePrefix: String)
//transient so that both Gson and Room ignore it
{
    @Transient
    @ColumnInfo(name = "upload_completed")  //^ So Room don't ignore it but Gson does
    var uploadCompleted: Boolean = false

    //To avoid passing around an ID when it's autogenerated
    //see https://medium.com/@kirillsuslov/how-to-start-using-room-b90d08eb3f0b
    @Ignore
    constructor(timestampEpoch: Long, filenamePrefix: String) : this(id = 0,
            timestamp = SimpleDateFormat(Utils.getSimpleDateFormatPattern(), Locale.US)
                    .format(Date(timestampEpoch)),
            filenamePrefix = filenamePrefix
    )
}